#dir und hostname#
tls_dir_names: acme
tls_vhostnames: 
  - denisubuntu.devops.rebrain.srwx.net
  - deniscentos.devops.rebrain.srwx.net
virtualconf_ubuntu:
  - {src: 'virt_hosts_443_ubuntu.conf.j2', dest: '/etc/nginx/conf.d/{{ tls_vhostnames.0 }}.conf', mode: '0755'}
virtualconf_redhat:
  - {src: 'virt_hosts_443_centos.conf.j2', dest: '/etc/nginx/conf.d/{{ tls_vhostnames.1 }}.conf', mode: '0755'}  
letsencrypt_renew_email: ramires@inbox.ru
