nginx_user_ubuntu: www-data
nginx_user_centos: nginx
listen_http: 80
worker_processes: auto
worker_connections: 1024
virtualconf_ubuntu:
  - {src: 'nginx_ubuntu.conf.j2', dest: '/etc/nginx/nginx.conf', mode: '0644'}
virtualconf_centos:
  - {src: 'nginx_centos.conf.j2', dest: '/etc/nginx/nginx.conf', mode: '0644'}  
