#dir und hostname#
dir_names_ubuntu:
  - acme
  - denisubuntu.devops.rebrain.srwx.net
dir_names_centos:
  - acme
  - deniscentos.devops.rebrain.srwx.net  

virtualconf_ubuntu:
  - {src: 'virt_hosts_ubuntu.conf.j2', dest: '/etc/nginx/conf.d/{{ dir_names_ubuntu.1 }}.conf', mode: '0755'}
  - {src: 'index_ubuntu.html.j2', dest: '/opt/www/{{ dir_names_ubuntu.1 }}/index.html', mode: '0644'}
virtualconf_centos:
  - {src: 'virt_hosts_centos.conf.j2', dest: '/etc/nginx/conf.d/{{ dir_names_centos.1 }}.conf', mode: '0755'}
  - {src: 'index_centos.html.j2', dest: '/opt/www/{{ dir_names_centos.1 }}/index.html', mode: '0644'}
listen_http: 80
listen_http2: 443




